### ISSUE TITLE
Failed to connect RatKeeper in benchmark with `thread_size=1000`.

### ISSUE THREAD

**Issue by JackyWoo** [JDRaftKeeper/RaftKeeper#123]
### Description
Failed to connect RatKeeper in benchmark.

The following log is for session connecting:
```
<Warning> NuRaft: [NOT OK] commit_ret_cv 54 wake up (2000065 us), return value (nil), result code -2
2023.12.07 10:32:34.685168 [ 58 ] <Error> NuRaft: session 6 failed to read rpc header from socket 11.148.135.40:34040 due to error 2, End of file, ref count 1
```

### How to reproduce 
Run benchmark with `thread_size=1000`

**Comment by JackyWoo** [comment]
By simplifying the benchmark tool  which only connection to server, and set thread_size to 200 we found only  catching 171 new connection.
```
grep "New connection from 10.203.46.164" raftkeeper.log |grep " 291" | grep -v timeout | wc -l
171
```

This is someting wrong with benchmark tool.

**Comment by JackyWoo** [comment]
And when benchmark completed we found all IO thread are stuck on the NuRaft auto-forwaring which is unexpected.

```
Thread 35 (Thread 0x7f6af06fb700 (LWP 1016 - IO-Hdlr#1)):
#0  0x00007f6b2b5a3a35 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000007e40a0 in __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) ()
#2  0x0000000000771b51 in pthread_cond_wait ()
#3  0x0000000000f1fde8 in __libcpp_condvar_wait (__cv=0x7b3c00077848, __m=0x80) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/libcxx/include/__threading_support:436
#4  std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) (this=0x7b3c00077848, lk=...) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/libcxx/src/condition_variable.cpp:44
#5  0x0000000000a7ac23 in nuraft::cmd_result<std::__1::shared_ptr<nuraft::buffer>, std::__1::shared_ptr<std::exception> >::get() (this=this@entry=0x7b3c000777a8) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/NuRaft/include/libnuraft/async.hxx:297
#6  0x0000000000a77e8c in nuraft::raft_server::send_msg_to_leader(std::__1::shared_ptr<nuraft::req_msg>&, nuraft::raft_server::req_ext_params const&) (this=this@entry=0x7b6c00000018, req=..., ext_params=...) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/NuRaft/src/handle_user_cmd.cxx:273
#7  0x0000000000a78c67 in nuraft::raft_server::append_entries_ext(std::__1::vector<std::__1::shared_ptr<nuraft::buffer>, std::__1::allocator<std::__1::shared_ptr<nuraft::buffer> > > const&, nuraft::raft_server::req_ext_params const&) (this=<optimized out>, this@entry=0x7b6c00000018, logs=..., ext_params=...) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/NuRaft/src/handle_user_cmd.cxx:109
#8  0x0000000000a788fb in nuraft::raft_server::append_entries(std::__1::vector<std::__1::shared_ptr<nuraft::buffer>, std::__1::allocator<std::__1::shared_ptr<nuraft::buffer> > > const&) (this=0x7b3c0007784c, logs=...) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/NuRaft/src/handle_user_cmd.cxx:84
#9  0x00000000008e1b11 in RK::KeeperServer::getSessionID(long) (this=0x7b4c000001d8, session_timeout_ms=10000) at /data1/home/wujianchao/project/jd/raftkeeper/src/Service/KeeperServer.cpp:154
#10 0x000000000089933b in getSessionID (this=0x7b6400001e18, session_timeout_ms=10000) at /data1/home/wujianchao/project/jd/raftkeeper/src/Service/KeeperDispatcher.h:115
#11 RK::ConnectionHandler::handleHandshake(RK::ConnectRequest&) (this=<optimized out>, this@entry=0x7b6400106d00, connect_req=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Service/ConnectionHandler.cpp:547
#12 0x000000000089411d in RK::ConnectionHandler::onSocketReadable(RK::Notification const&) (this=this@entry=0x7b6400106d00) at /data1/home/wujianchao/project/jd/raftkeeper/src/Service/ConnectionHandler.cpp:198
#13 0x000000000089e74f in RK::Observer<RK::ConnectionHandler, RK::ReadableNotification>::notify(RK::Notification const&) const (this=<optimized out>, notification=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/Observer.h:74
#14 0x00000000008723f9 in RK::NotificationCenter::postNotification(RK::Notification const&) (this=<optimized out>, notification=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/NotificationCenter.cpp:89
#15 0x0000000000873421 in RK::SocketNotifier::dispatch(RK::Notification const&) (this=0x7b3c0007784c, notification=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/SocketNotifier.cpp:34
#16 0x000000000086c8fd in RK::SocketReactor::dispatch(std::__1::shared_ptr<RK::SocketNotifier>&, RK::Notification const&) (this=this@entry=0x7b540000ed98, notifier=..., notification=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/SocketReactor.cpp:310
#17 0x000000000086a546 in dispatch (this=0x7b540000ed98, socket=..., notification=...) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/SocketReactor.cpp:282
#18 RK::SocketReactor::run() (this=this@entry=0x7b540000ed98) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/SocketReactor.cpp:67
#19 0x000000000086cdd4 in RK::AsyncSocketReactor::run() (this=0x7b540000ed98) at /data1/home/wujianchao/project/jd/raftkeeper/src/Common/NIO/SocketReactor.cpp:336
#20 0x0000000000cd4a50 in Poco::(anonymous namespace)::RunnableHolder::run() (this=<optimized out>) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/poco/Foundation/src/Thread.cpp:56
#21 0x0000000000cd3137 in Poco::ThreadImpl::runnableEntry(void*) (pThread=0x7b540000eec0) at /data1/home/wujianchao/project/jd/raftkeeper/contrib/poco/Foundation/src/Thread_POSIX.cpp:358
#22 0x0000000000770e3d in __tsan_thread_start_func ()
#23 0x00007f6b2b59fea5 in start_thread () from /lib64/libpthread.so.0
#24 0x00007f6b2bdbcb0d in clone () from /lib64/libc.so.6

```
