### ISSUE TITLE
The CPU usage is very high occasionally.

### ISSUE THREAD

**Issue by JackyWoo** [JDRaftKeeper/RaftKeeper#85]
### RaftKeeper version
v2.0.1

### Description
Occasionally, the CPU usage is very high.

**Comment by JackyWoo** [comment]
Top 10 thread
```
ps -Lp 73 -o tid,lwp,comm,pcpu | sort -k4 -nr | head
   281    281 raftkeeper      71.8
   188    188 raftkeeper      40.5
    79     79 ReqProcessor     0.8
    84     84 raftkeeper       0.2
    83     83 raftkeeper       0.2
    81     81 raftkeeper       0.2
    78     78 raftkeeper       0.2
    77     77 raftkeeper       0.2
    76     76 raftkeeper       0.2
   153    153 RspDispatcher    0.2
```

```
Thread 164 (Thread 0x7f0ed3ba6700 (LWP 281)):
#0  0x0000000000ba5e49 in __syscall ()
#1  0x0000000000ba5091 in clock_gettime ()
#2  0x0000000000a4f727 in Poco::Timestamp::update() ()
#3  0x000000000072a91b in RK::PollSetImpl::poll(Poco::Timespan const&) ()
#4  0x000000000072a41c in RK::PollSet::poll(Poco::Timespan const&) ()
#5  0x0000000000727dcb in RK::SocketReactor::run() ()
#6  0x0000000000a4da95 in Poco::ThreadImpl::runnableEntry(void*) ()
#7  0x00007f0f6da6dea5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f0f6e28ab0d in clone () from /lib64/libc.so.6


Thread 257 (Thread 0x7f0f035ff700 (LWP 188)):
#0  0x0000000000ba5e49 in __syscall ()
#1  0x0000000000ba52f3 in epoll_wait ()
#2  0x000000000072a90e in RK::PollSetImpl::poll(Poco::Timespan const&) ()
#3  0x000000000072a41c in RK::PollSet::poll(Poco::Timespan const&) ()
#4  0x0000000000727dcb in RK::SocketReactor::run() ()
#5  0x0000000000a4da95 in Poco::ThreadImpl::runnableEntry(void*) ()
#6  0x00007f0f6da6dea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f0f6e28ab0d in clone () from /lib64/libc.so.6

```
